/*
 * Generated by MTK SP DrvGen Version: 2.2.160113 for MT6797. Copyright MediaTek Inc. (C) 2015.
 * 01.18.2022 23:42:18
 * Do Not Modify the File.
 */

#ifndef __CUST_ADC_H
#define __CUST_ADC_H

#define AUXADC_TEMPERATURE_CHANNEL			0
#define AUXADC_TEMPERATURE1_CHANNEL			1
#define AUXADC_ADC_FDD_RF_PARAMS_DYNAMIC_CUSTOM_CH_CHANNEL			2


#endif /* __CUST_ADC_H */

