/*
 * Generated by MTK SP DrvGen Version: 2.2.160113 for MT6797. Copyright MediaTek Inc. (C) 2015.
 * 01.18.2022 23:42:18
 * Do Not Modify the File.
 */

#ifndef __CUST_POWER_H
#define __CUST_POWER_H

#define GPIO_DVDD28_MC1		GPIO_VMC
#define GPIO_DVDD28_SIM		GPIO_VIO18
#define GPIO_DVDD28_SIM2		GPIO_VIO18


#endif /* __CUST_POWER_H */

