/*
 * Generated by MTK SP DrvGen Version: 2.2.160113 for MT6797. Copyright MediaTek Inc. (C) 2015.
 * 01.18.2022 23:42:18
 * Do Not Modify the File.
 */

#include <linux/types.h>
#include <mach/mt_typedefs.h>
#include <mach/upmu_common.h>
#include <mach/upmu_hw.h>
#include <mach/mt_pm_ldo.h>

void pmu_drv_tool_customization_init(void)
{
	pmic_set_register_value(MT6351_PMIC_RG_VCAMA_EN,0);
	pmic_set_register_value(MT6351_PMIC_RG_VSIM1_EN,0);
	pmic_set_register_value(MT6351_PMIC_RG_VSIM2_EN,0);
	pmic_set_register_value(MT6351_PMIC_RG_VLDO28_EN_0,0);
	pmic_set_register_value(MT6351_PMIC_RG_VIBR_EN,0);
	pmic_set_register_value(MT6351_PMIC_RG_VCAMD_EN,0);
	pmic_set_register_value(MT6351_PMIC_RG_VCAMIO_EN,0);
}

