#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

ccflags-y += -I$(srctree)/arch/arm64/boot/dts

obj-y += nt35532_fhd_boe_vdo_lcm.o
